app:
  message: This is the DEV Environment Property file
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test
    userName: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect