server:
  port: 8080
  http2:
    enabled: true

spring:
  profiles:
    active: dev
  jpa:
    generate_statistics: false
    datasource:
      hikari:
        connectionTimeout: 30000
        idleTimeout: 600000
        maxLifetime: 1800000
    jdbc:
      time_zone: UTC
      batch_size: 10


  logging:
    level:
      org.springframework.context: debug
      org.springframework.web: debug
      org.hibernate: debug