app:
  message: This is the TEST Environment property file
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    userName: root
    password: Password01
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect