app:
  message: This is the Dev Environment property file
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blogdb?useSSL=false
    userName: root
    password: Password01
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      # The property spring.jpa.hibernate.ddl-auto is important.
      # It tries to validate the database schema according to the entities that you have created in the application and throws an error if the schema doesn’t match the entity specifications.
      ddl-auto: validate
      generate-ddl: true
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect # The SQL dialect makes Hibernate generate better SQL for the chosen database

    flayway:
      baselineOnMigrate: true
      check-location: true
      locations: classpath:db/migration
      enabled: true
      #schemas: myblogdb if you want to create database schema but you have to anotatate you entity class with @Table(schema ="myblogDB") or @Table(catlog ="mublogdb")

management:
  endpoints:
    web:
      exposure:
        include: info,health,flyway